/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MVCproj.FirstApp.JspInPrivatePlace;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
