/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MVCProj.WishApp.AbstractController.PVC.DirectoryMatchUrlPattern;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
